# -*- coding: utf-8 -*-
"""Sai Kamal Reddy Muthanagari PDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11E31iLCM5sbnw5j8E2Zl-jC4sBNBvuk8
"""

# General utilities
import warnings

# Data preparation and analysis
import numpy as np
import pandas as pd

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Google Colab and notebook display
from google.colab import files
from IPython.display import display

# Data splitting
from sklearn.model_selection import train_test_split

# Data preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Machine-learning models
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

# Model evaluation
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    log_loss,
    roc_auc_score,
    roc_curve
)

# Notebook settings
warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid", palette="colorblind")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 160)

# Reproducibility setting
RANDOM_STATE = 42

claims_raw = pd.read_csv('/content/aurorasure_claims.csv')
policyholders_raw = pd.read_excel('/content/aurorasure_policyholders.xlsx',sheet_name="Sheet1",engine="openpyxl")

display(claims_raw.head())
display(policyholders_raw.head())

"""## **Standardise column names and confirm the schemas**"""

def standardise_column_names(dataframe):
    dataframe = dataframe.copy()
    dataframe.columns = (
        dataframe.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return dataframe

claims = standardise_column_names(claims_raw)
policyholders = standardise_column_names(policyholders_raw)

expected_claims_columns = {
    "claim_id",
    "policy_id",
    "claim_type",
    "claim_amount",
    "days_since_policy_start",
    "num_prior_claims",
    "incident_report_delay_days",
    "is_weekend_claim",
    "claim_channel",
    "fraud_label"
}

expected_policyholder_columns = {
    "policy_id",
    "age",
    "gender",
    "postcode_region",
    "income_band",
    "policy_type",
    "policy_tenure_years",
    "fraud_label"
}

assert expected_claims_columns.issubset(claims.columns), (
    f"Missing claims columns: {expected_claims_columns - set(claims.columns)}"
)

assert expected_policyholder_columns.issubset(policyholders.columns), (
    f"Missing policyholder columns: "
    f"{expected_policyholder_columns - set(policyholders.columns)}"
)

"""# **Safely combine the datasets**"""

assert len(claims) == len(policyholders), (
    "The files have different row counts and require further key investigation."
)

assert claims["policy_id"].equals(policyholders["policy_id"]), (
    "The policy_id sequence differs between the files."
)

assert claims["fraud_label"].equals(policyholders["fraud_label"]), (
    "The two fraud_label columns do not agree."
)

claims["_policy_occurrence"] = claims.groupby("policy_id").cumcount()
policyholders["_policy_occurrence"] = (
    policyholders.groupby("policy_id").cumcount()
)

policyholders_for_merge = policyholders.drop(columns=["fraud_label"])

insurance_data = claims.merge(
    policyholders_for_merge,
    on=["policy_id", "_policy_occurrence"],
    how="inner",
    validate="one_to_one"
)

insurance_data = insurance_data.drop(columns=["_policy_occurrence"])

assert len(insurance_data) == len(claims) == 6000
assert insurance_data["claim_id"].is_unique
assert insurance_data.columns.tolist().count("fraud_label") == 1

print("Combined shape:", insurance_data.shape)
print("Fraud label columns:", [
    column for column in insurance_data.columns
    if "fraud_label" in column
])

display(insurance_data.head())

insurance_data.to_csv(
    "Insurance Data.csv",
    index=False
)


print("Merged dataset saved successfully as CSV")

"""# **Insurance Data Exploration**"""

print("\nData types:")
display(
    insurance_data.dtypes
    .rename("data_type")
    .to_frame()
)

print("\nDataFrame information:")
insurance_data.info()

"""## **Missing values, Duplicates, and valid categories**"""

quality_summary = pd.DataFrame({
    "data_type": insurance_data.dtypes.astype(str),
    "missing_count": insurance_data.isna().sum(),
    "missing_percentage": insurance_data.isna().mean().mul(100).round(2),
    "unique_values": insurance_data.nunique(dropna=False)
})

display(quality_summary)

print("Complete duplicate rows:", insurance_data.duplicated().sum())
print("Duplicated claim IDs:", insurance_data["claim_id"].duplicated().sum())
print("Duplicated policy IDs:", insurance_data["policy_id"].duplicated().sum())
print("Unique claim IDs:", insurance_data["claim_id"].nunique())
print("Unique policy IDs:", insurance_data["policy_id"].nunique())

valid_categories = {
    "claim_type": {"Motor", "Home", "Travel"},
    "claim_channel": {"Online", "Phone", "Broker"},
    "gender": {"Female", "Male", "Other"},
    "postcode_region": {
        "North", "South", "Midlands", "London", "Wales", "Scotland"
    },
    "income_band": {"Low", "Medium", "High"},
    "policy_type": {"Basic", "Standard", "Premium"},
    "is_weekend_claim": {0, 1},
    "fraud_label": {0, 1}
}

for column, accepted_values in valid_categories.items():
    observed_values = set(insurance_data[column].dropna().unique())
    unexpected_values = observed_values - accepted_values
    print(
        f"{column}: observed={sorted(observed_values)}, "
        f"unexpected={sorted(unexpected_values)}"
    )

"""# **Descriptive statistics and Category distributions**"""

numeric_columns = insurance_data.select_dtypes(include=np.number).columns
categorical_columns = insurance_data.select_dtypes(exclude=np.number).columns

print("Numerical summary:")
display(insurance_data[numeric_columns].describe().T)

for column in categorical_columns:
    print(f"\nDistribution of {column}:")
    category_table = pd.DataFrame({
        "count": insurance_data[column].value_counts(dropna=False),
        "percentage": insurance_data[column]
        .value_counts(normalize=True, dropna=False)
        .mul(100)
        .round(2)
    })
    display(category_table)

"""# **Detect outliers using the IQR method**"""

def calculate_iqr_outliers(dataframe, columns):
    results = []

    for column in columns:
        q1 = dataframe[column].quantile(0.25)
        q3 = dataframe[column].quantile(0.75)
        iqr = q3 - q1
        lower_limit = q1 - 1.5 * iqr
        upper_limit = q3 + 1.5 * iqr

        outlier_mask = (
            (dataframe[column] < lower_limit) |
            (dataframe[column] > upper_limit)
        )

        results.append({
            "variable": column,
            "q1": q1,
            "q3": q3,
            "iqr": iqr,
            "lower_limit": lower_limit,
            "upper_limit": upper_limit,
            "outlier_count": int(outlier_mask.sum()),
            "outlier_percentage": round(outlier_mask.mean() * 100, 2)
        })

    return pd.DataFrame(results)

outlier_columns = [
    "claim_amount",
    "incident_report_delay_days",
    "days_since_policy_start",
    "num_prior_claims",
    "age",
    "policy_tenure_years"
]

outlier_summary = calculate_iqr_outliers(
    insurance_data,
    outlier_columns
)

display(outlier_summary)

"""## **Outlier plot 1: claim amount**"""

plt.figure(figsize=(10, 4))
sns.boxplot(
    data=insurance_data,
    x="claim_amount",
    color="#4C78A8"
)
plt.title("Outlier assessment: claim amount")
plt.xlabel("Claim amount (£)")
plt.tight_layout()
plt.show()

"""## **Outlier plot 2: policy tenure**"""

plt.figure(figsize=(10, 4))
sns.boxplot(
    data=insurance_data,
    x="policy_tenure_years",
    color="#F58518"
)
plt.title("Outlier assessment: policy tenure")
plt.xlabel("Policy tenure (years)")
plt.tight_layout()
plt.show()

"""# **Clean and validate the combined data**"""

insurance_clean = insurance_data.copy()

text_columns = insurance_clean.select_dtypes(include="object").columns

for column in text_columns:
    insurance_clean[column] = (
        insurance_clean[column]
        .astype("string")
        .str.strip()
        .str.title()
    )

insurance_clean = insurance_clean.drop_duplicates().copy()

numeric_nonnegative_columns = [
    "claim_amount",
    "days_since_policy_start",
    "num_prior_claims",
    "incident_report_delay_days",
    "policy_tenure_years"
]

for column in numeric_nonnegative_columns:
    invalid_mask = insurance_clean[column] < 0
    insurance_clean.loc[invalid_mask, column] = np.nan

insurance_clean.loc[
    ~insurance_clean["age"].between(18, 100),
    "age"
] = np.nan

insurance_clean.loc[
    ~insurance_clean["is_weekend_claim"].isin([0, 1]),
    "is_weekend_claim"
] = np.nan

insurance_clean.loc[
    ~insurance_clean["fraud_label"].isin([0, 1]),
    "fraud_label"
] = np.nan

assert insurance_clean["claim_id"].is_unique
assert insurance_clean["claim_id"].gt(0).all()
assert insurance_clean["policy_id"].gt(0).all()
assert insurance_clean["fraud_label"].notna().all()

print("Cleaned shape:", insurance_clean.shape)
print("Remaining missing values:", insurance_clean.isna().sum().sum())
display(insurance_clean.head())

"""# **Descriptive Statistics**"""

def add_count_labels(axis, decimal_places=0):
    for container in axis.containers:
        labels = []

        for bar in container:
            height = bar.get_height()

            if np.isnan(height):
                labels.append("")
            elif decimal_places == 0:
                labels.append(f"{height:,.0f}")
            else:
                labels.append(f"{height:,.{decimal_places}f}")

        axis.bar_label(
            container,
            labels=labels,
            padding=3,
            fontsize=9
        )

def add_percentage_labels(axis, decimal_places=1):
    for container in axis.containers:
        labels = []

        for bar in container:
            height = bar.get_height()

            if np.isnan(height):
                labels.append("")
            else:
                labels.append(
                    f"{height:.{decimal_places}f}%"
                )

        axis.bar_label(
            container,
            labels=labels,
            padding=3,
            fontsize=9
        )

def format_chart(axis, title, xlabel, ylabel):
    axis.set_title(title, fontsize=14, fontweight="bold", pad=14)
    axis.set_xlabel(xlabel, fontsize=11)
    axis.set_ylabel(ylabel, fontsize=11)
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)

"""## **Number of records**"""

number_of_records = len(insurance_clean)

record_summary = pd.DataFrame({
    "measure": ["Number of insurance claims"],
    "value": [number_of_records]
})

display(record_summary)

print(f"Number of records: {number_of_records:,}")

"""## **Percentage of fraudulent claims**"""

fraud_count = int(insurance_clean["fraud_label"].sum())
legitimate_count = int(
    (insurance_clean["fraud_label"] == 0).sum()
)
fraud_percentage = (
    insurance_clean["fraud_label"].mean() * 100
)

fraud_summary = pd.DataFrame({
    "claim_status": ["Legitimate", "Fraudulent", "Total"],
    "number_of_claims": [
        legitimate_count,
        fraud_count,
        number_of_records
    ],
    "percentage": [
        legitimate_count / number_of_records * 100,
        fraud_percentage,
        100
    ]
})

display(fraud_summary.round(2))

print(f"Fraudulent claims: {fraud_count:,}")
print(f"Fraud percentage: {fraud_percentage:.2f}%")

"""## **Plot legitimate and fraudulent claim proportions**"""

fraud_status_plot = (
    insurance_clean["fraud_label"]
    .map({0: "Legitimate", 1: "Fraudulent"})
    .value_counts()
    .rename_axis("claim_status")
    .reset_index(name="number_of_claims")
)

fraud_status_plot["percentage"] = (
    fraud_status_plot["number_of_claims"]
    / fraud_status_plot["number_of_claims"].sum()
    * 100
)

fig, axis = plt.subplots(figsize=(8, 5))

bars = axis.bar(
    fraud_status_plot["claim_status"],
    fraud_status_plot["percentage"],
    color=["#2A9D8F", "#E76F51"],
    edgecolor="black",
    linewidth=0.7
)

axis.bar_label(
    bars,
    labels=[
        f"{percentage:.2f}%"
        for percentage in fraud_status_plot["percentage"]
    ],
    padding=4,
    fontsize=10,
    fontweight="bold"
)

format_chart(
    axis,
    "Percentage of legitimate and fraudulent claims",
    "Claim status",
    "Percentage of claims"
)

axis.set_ylim(
    0,
    fraud_status_plot["percentage"].max() * 1.15
)

plt.tight_layout()
plt.show()

"""## **Fraud rate by claim type**"""

fraud_by_claim_type = (
    insurance_clean
    .groupby("claim_type", observed=False)["fraud_label"]
    .agg(
        total_claims="size",
        fraudulent_claims="sum",
        fraud_rate="mean"
    )
    .reset_index()
)

fraud_by_claim_type["fraud_rate_percentage"] = (
    fraud_by_claim_type["fraud_rate"] * 100
)

fraud_by_claim_type = fraud_by_claim_type.sort_values(
    "fraud_rate_percentage",
    ascending=False
)

display(fraud_by_claim_type.round(2))

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    fraud_by_claim_type["claim_type"],
    fraud_by_claim_type["fraud_rate_percentage"],
    color=["#6A4C93", "#8AC926", "#FFCA3A"],
    edgecolor="black",
    linewidth=0.7
)

axis.bar_label(
    bars,
    labels=[
        f"{value:.2f}%"
        for value in fraud_by_claim_type[
            "fraud_rate_percentage"
        ]
    ],
    padding=4,
    fontsize=10,
    fontweight="bold"
)

format_chart(
    axis,
    "Fraud rate by claim type",
    "Claim type",
    "Fraud rate (%)"
)

axis.set_ylim(
    0,
    fraud_by_claim_type["fraud_rate_percentage"].max() * 1.20
)

plt.tight_layout()
plt.show()

"""# **Mean, median, standard deviation and IQR**"""

descriptive_variables = [
    "claim_amount",
    "incident_report_delay_days",
    "days_since_policy_start"
]

descriptive_statistics = pd.DataFrame({
    "mean": insurance_clean[descriptive_variables].mean(),
    "median": insurance_clean[descriptive_variables].median(),
    "standard_deviation": (
        insurance_clean[descriptive_variables].std()
    ),
    "first_quartile": (
        insurance_clean[descriptive_variables].quantile(0.25)
    ),
    "third_quartile": (
        insurance_clean[descriptive_variables].quantile(0.75)
    )
})

descriptive_statistics["interquartile_range"] = (
    descriptive_statistics["third_quartile"]
    - descriptive_statistics["first_quartile"]
)

descriptive_statistics = (
    descriptive_statistics
    .reset_index()
    .rename(columns={"index": "variable"})
)

display(descriptive_statistics.round(2))

"""# **Distribution plots**

### **Plot the distribution of claim amount**
"""

claim_amount_counts, claim_amount_bins = np.histogram(
    insurance_clean["claim_amount"].dropna(),
    bins=20
)

claim_amount_centres = (
    claim_amount_bins[:-1] + claim_amount_bins[1:]
) / 2

claim_amount_widths = np.diff(claim_amount_bins)

fig, axis = plt.subplots(figsize=(11, 6))

bars = axis.bar(
    claim_amount_centres,
    claim_amount_counts,
    width=claim_amount_widths * 0.90,
    color="#0077B6",
    edgecolor="white"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}" if count > 0 else ""
        for count in claim_amount_counts
    ],
    padding=2,
    fontsize=7,
    rotation=90
)

mean_claim_amount = insurance_clean["claim_amount"].mean()
median_claim_amount = insurance_clean["claim_amount"].median()

axis.axvline(
    mean_claim_amount,
    color="#D00000",
    linestyle="--",
    linewidth=2,
    label=f"Mean: £{mean_claim_amount:,.2f}"
)

axis.axvline(
    median_claim_amount,
    color="#FFBA08",
    linestyle="-.",
    linewidth=2,
    label=f"Median: £{median_claim_amount:,.2f}"
)

format_chart(
    axis,
    "Distribution of claim amount",
    "Claim amount (£)",
    "Number of claims"
)

axis.legend()
axis.margins(y=0.18)

plt.tight_layout()
plt.show()

"""### **Plot the distribution of reporting delay**"""

reporting_delay_counts = (
    insurance_clean["incident_report_delay_days"]
    .value_counts()
    .sort_index()
)

fig, axis = plt.subplots(figsize=(11, 6))

bars = axis.bar(
    reporting_delay_counts.index.astype(str),
    reporting_delay_counts.values,
    color="#F77F00",
    edgecolor="black",
    linewidth=0.5
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}"
        for count in reporting_delay_counts.values
    ],
    padding=3,
    fontsize=8
)

format_chart(
    axis,
    "Distribution of incident reporting delay",
    "Incident reporting delay (days)",
    "Number of claims"
)

axis.margins(y=0.15)

plt.tight_layout()
plt.show()

"""## **Plot the distribution of days since policy start**"""

policy_days_counts, policy_days_bins = np.histogram(
    insurance_clean["days_since_policy_start"].dropna(),
    bins=20
)

policy_days_centres = (
    policy_days_bins[:-1] + policy_days_bins[1:]
) / 2

policy_days_widths = np.diff(policy_days_bins)

fig, axis = plt.subplots(figsize=(11, 6))

bars = axis.bar(
    policy_days_centres,
    policy_days_counts,
    width=policy_days_widths * 0.90,
    color="#7209B7",
    edgecolor="white"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}" if count > 0 else ""
        for count in policy_days_counts
    ],
    padding=2,
    fontsize=7,
    rotation=90
)

mean_policy_days = (
    insurance_clean["days_since_policy_start"].mean()
)
median_policy_days = (
    insurance_clean["days_since_policy_start"].median()
)

axis.axvline(
    mean_policy_days,
    color="#06D6A0",
    linestyle="--",
    linewidth=2,
    label=f"Mean: {mean_policy_days:,.2f} days"
)

axis.axvline(
    median_policy_days,
    color="#FFD166",
    linestyle="-.",
    linewidth=2,
    label=f"Median: {median_policy_days:,.2f} days"
)

format_chart(
    axis,
    "Distribution of days since policy start",
    "Days since policy start",
    "Number of claims"
)

axis.legend()
axis.margins(y=0.18)

plt.tight_layout()
plt.show()

"""# **Mean and median claim amount by fraud label**

### **Claim amount by fraud label**
"""

claim_amount_by_fraud = (
    insurance_clean
    .assign(
        claim_status=insurance_clean["fraud_label"].map({
            0: "Legitimate",
            1: "Fraudulent"
        })
    )
    .groupby("claim_status", observed=False)["claim_amount"]
    .agg(
        number_of_claims="size",
        mean_claim_amount="mean",
        median_claim_amount="median"
    )
    .reset_index()
)

display(claim_amount_by_fraud.round(2))

claim_amount_long = claim_amount_by_fraud.melt(
    id_vars="claim_status",
    value_vars=[
        "mean_claim_amount",
        "median_claim_amount"
    ],
    var_name="measure",
    value_name="claim_amount"
)

claim_amount_long["measure"] = (
    claim_amount_long["measure"]
    .map({
        "mean_claim_amount": "Mean",
        "median_claim_amount": "Median"
    })
)

fig, axis = plt.subplots(figsize=(10, 6))

sns.barplot(
    data=claim_amount_long,
    x="claim_status",
    y="claim_amount",
    hue="measure",
    palette={
        "Mean": "#00B4D8",
        "Median": "#FF006E"
    },
    edgecolor="black",
    ax=axis
)

for container in axis.containers:
    axis.bar_label(
        container,
        labels=[
            f"£{bar.get_height():,.2f}"
            for bar in container
        ],
        padding=4,
        fontsize=9
    )

format_chart(
    axis,
    "Mean and median claim amount by fraud label",
    "Claim status",
    "Claim amount (£)"
)

axis.legend(title="Statistic")
axis.margins(y=0.18)

plt.tight_layout()
plt.show()

"""## **Distribution of claim type, channel and policy type**"""

def category_distribution(dataframe, column):
    output = (
        dataframe[column]
        .value_counts(dropna=False)
        .rename_axis(column)
        .reset_index(name="number_of_claims")
    )

    output["percentage"] = (
        output["number_of_claims"]
        / output["number_of_claims"].sum()
        * 100
    )

    return output

claim_type_distribution = category_distribution(
    insurance_clean,
    "claim_type"
)

claim_channel_distribution = category_distribution(
    insurance_clean,
    "claim_channel"
)

policy_type_distribution = category_distribution(
    insurance_clean,
    "policy_type"
)

print("Claim type distribution:")
display(claim_type_distribution.round(2))

print("Claim channel distribution:")
display(claim_channel_distribution.round(2))

print("Policy type distribution:")
display(policy_type_distribution.round(2))

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    claim_type_distribution["claim_type"],
    claim_type_distribution["number_of_claims"],
    color=["#264653", "#2A9D8F", "#E9C46A"],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}\n({percentage:.1f}%)"
        for count, percentage in zip(
            claim_type_distribution["number_of_claims"],
            claim_type_distribution["percentage"]
        )
    ],
    padding=4,
    fontsize=9
)

format_chart(
    axis,
    "Distribution of claim type",
    "Claim type",
    "Number of claims"
)

axis.margins(y=0.20)

plt.tight_layout()
plt.show()

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    claim_channel_distribution["claim_channel"],
    claim_channel_distribution["number_of_claims"],
    color=["#F94144", "#F3722C", "#F8961E"],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}\n({percentage:.1f}%)"
        for count, percentage in zip(
            claim_channel_distribution["number_of_claims"],
            claim_channel_distribution["percentage"]
        )
    ],
    padding=4,
    fontsize=9
)

format_chart(
    axis,
    "Distribution of claim channel",
    "Claim channel",
    "Number of claims"
)

axis.margins(y=0.20)

plt.tight_layout()
plt.show()

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    policy_type_distribution["policy_type"],
    policy_type_distribution["number_of_claims"],
    color=["#577590", "#43AA8B", "#90BE6D"],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}\n({percentage:.1f}%)"
        for count, percentage in zip(
            policy_type_distribution["number_of_claims"],
            policy_type_distribution["percentage"]
        )
    ],
    padding=4,
    fontsize=9
)

format_chart(
    axis,
    "Distribution of policy type",
    "Policy type",
    "Number of claims"
)

axis.margins(y=0.20)

plt.tight_layout()
plt.show()

"""# **Fraud rate by region, income band and policy type**"""

def calculate_fraud_rate(dataframe, group_column):
    result = (
        dataframe
        .groupby(group_column, observed=False)["fraud_label"]
        .agg(
            total_claims="size",
            fraudulent_claims="sum",
            fraud_rate="mean"
        )
        .reset_index()
    )

    result["fraud_rate_percentage"] = (
        result["fraud_rate"] * 100
    )

    return result.sort_values(
        "fraud_rate_percentage",
        ascending=False
    )

fraud_by_region = calculate_fraud_rate(
    insurance_clean,
    "postcode_region"
)

fraud_by_income = calculate_fraud_rate(
    insurance_clean,
    "income_band"
)

fraud_by_policy_type = calculate_fraud_rate(
    insurance_clean,
    "policy_type"
)

print("Fraud rate by region:")
display(fraud_by_region.round(2))

print("Fraud rate by income band:")
display(fraud_by_income.round(2))

print("Fraud rate by policy type:")
display(fraud_by_policy_type.round(2))

"""## **Plot fraud rate by region**"""

fig, axis = plt.subplots(figsize=(11, 6))

bars = axis.bar(
    fraud_by_region["postcode_region"],
    fraud_by_region["fraud_rate_percentage"],
    color=[
        "#003F5C",
        "#2F4B7C",
        "#665191",
        "#A05195",
        "#D45087",
        "#F95D6A"
    ],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{value:.2f}%"
        for value in fraud_by_region["fraud_rate_percentage"]
    ],
    padding=4,
    fontsize=9
)

format_chart(
    axis,
    "Fraud rate by postcode region",
    "Postcode region",
    "Fraud rate (%)"
)

axis.margins(y=0.20)
plt.xticks(rotation=20)

plt.tight_layout()
plt.show()

"""## **Plot fraud rate by income band**"""

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    fraud_by_income["income_band"],
    fraud_by_income["fraud_rate_percentage"],
    color=["#9B2226", "#BB3E03", "#CA6702"],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{value:.2f}%"
        for value in fraud_by_income["fraud_rate_percentage"]
    ],
    padding=4,
    fontsize=10
)

format_chart(
    axis,
    "Fraud rate by income band",
    "Income band",
    "Fraud rate (%)"
)

axis.margins(y=0.20)

plt.tight_layout()
plt.show()

"""## **Plot fraud rate by policy type**"""

fig, axis = plt.subplots(figsize=(9, 5))

bars = axis.bar(
    fraud_by_policy_type["policy_type"],
    fraud_by_policy_type["fraud_rate_percentage"],
    color=["#386641", "#6A994E", "#A7C957"],
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{value:.2f}%"
        for value in fraud_by_policy_type[
            "fraud_rate_percentage"
        ]
    ],
    padding=4,
    fontsize=10
)

format_chart(
    axis,
    "Fraud rate by policy type",
    "Policy type",
    "Fraud rate (%)"
)

axis.margins(y=0.20)

plt.tight_layout()
plt.show()

"""## **Age distribution**"""

age_counts, age_bins = np.histogram(
    insurance_clean["age"].dropna(),
    bins=range(15, 91, 5)
)

age_centres = (
    np.array(age_bins[:-1]) + np.array(age_bins[1:])
) / 2

age_widths = np.diff(age_bins)

fig, axis = plt.subplots(figsize=(11, 6))

bars = axis.bar(
    age_centres,
    age_counts,
    width=age_widths * 0.85,
    color="#00A6A6",
    edgecolor="black"
)

axis.bar_label(
    bars,
    labels=[
        f"{count:,}" if count > 0 else ""
        for count in age_counts
    ],
    padding=3,
    fontsize=8
)

mean_age = insurance_clean["age"].mean()
median_age = insurance_clean["age"].median()

axis.axvline(
    mean_age,
    color="#EF476F",
    linestyle="--",
    linewidth=2,
    label=f"Mean age: {mean_age:.2f}"
)

axis.axvline(
    median_age,
    color="#FFD166",
    linestyle="-.",
    linewidth=2,
    label=f"Median age: {median_age:.2f}"
)

format_chart(
    axis,
    "Age distribution of claimants",
    "Age",
    "Number of claims"
)

axis.legend()
axis.margins(y=0.18)

plt.tight_layout()
plt.show()

"""## **Gender proportion and fraud rate by gender**"""

gender_proportion = (
    insurance_clean["gender"]
    .value_counts(dropna=False)
    .rename_axis("gender")
    .reset_index(name="number_of_claims")
)

gender_proportion["percentage"] = (
    gender_proportion["number_of_claims"]
    / gender_proportion["number_of_claims"].sum()
    * 100
)

display(gender_proportion.round(2))

"""## **Fraud rate by gender**"""

fraud_by_gender = calculate_fraud_rate(
    insurance_clean,
    "gender"
)

display(fraud_by_gender.round(2))

"""## **Relationships among numeric variables**"""

relationship_variables = [
    "claim_amount",
    "num_prior_claims",
    "policy_tenure_years",
    "days_since_policy_start"
]

relationship_correlation = (
    insurance_clean[relationship_variables]
    .corr(method="pearson")
)

display(relationship_correlation.round(3))

friendly_relationship_labels = {
    "claim_amount": "Claim amount",
    "num_prior_claims": "Prior claims",
    "policy_tenure_years": "Policy tenure",
    "days_since_policy_start": "Days since policy start"
}

labelled_correlation = relationship_correlation.rename(
    index=friendly_relationship_labels,
    columns=friendly_relationship_labels
)

fig, axis = plt.subplots(figsize=(13, 7))

sns.heatmap(
    labelled_correlation,
    annot=True,
    fmt=".3f",
    cmap="PuBuGn",
    vmin=-1,
    vmax=1,
    center=0,
    square=True,
    linewidths=1,
    linecolor="white",
    cbar_kws={"label": "Pearson correlation"},
    ax=axis
)

axis.set_title(
    "Relationships among claim and policy variables",
    fontsize=14,
    fontweight="bold",
    pad=15
)

plt.xticks(rotation=25, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""# **Data Preparation**

## **Inspect the target-variable balance**
"""

target_distribution = (
    insurance_clean["fraud_label"]
    .value_counts()
    .sort_index()
    .rename_axis("fraud_label")
    .reset_index(name="number_of_claims")
)

target_distribution["claim_status"] = (
    target_distribution["fraud_label"]
    .map({
        0: "Legitimate",
        1: "Fraudulent"
    })
)

target_distribution["percentage"] = (
    target_distribution["number_of_claims"]
    / target_distribution["number_of_claims"].sum()
    * 100
)

display(
    target_distribution[
        [
            "fraud_label",
            "claim_status",
            "number_of_claims",
            "percentage"
        ]
    ].round(2)
)

print(
    "Fraud prevalence:",
    f"{insurance_clean['fraud_label'].mean():.2%}"
)

target_column = "fraud_label"

identifier_columns = [
    "claim_id",
    "policy_id"
]

sensitive_columns = [
    "age",
    "gender"
]

excluded_columns = (
    identifier_columns
    + sensitive_columns
    + [target_column]
)

X = insurance_clean.drop(columns=excluded_columns).copy()
y = insurance_clean[target_column].astype(int).copy()

fairness_data = insurance_clean[
    [
        "age",
        "gender",
        "postcode_region",
        "income_band",
        "policy_type"
    ]
].copy()

print("Model features:")
print(X.columns.tolist())

print("\nExcluded identifiers:")
print(identifier_columns)

print("\nExcluded sensitive characteristics:")
print(sensitive_columns)

print("\nTarget distribution:")
print(y.value_counts())

"""## **Separate numerical and categorical features**"""

numerical_features = (
    X.select_dtypes(include=np.number)
    .columns
    .tolist()
)

categorical_features = (
    X.select_dtypes(exclude=np.number)
    .columns
    .tolist()
)

print("Numerical features:")
print(numerical_features)

print("\nCategorical features:")
print(categorical_features)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=RANDOM_STATE
)

print("Training records:", len(X_train))
print("Test records:", len(X_test))

print(
    "Training fraud rate:",
    f"{y_train.mean():.2%}"
)

print(
    "Test fraud rate:",
    f"{y_test.mean():.2%}"
)

assert len(X_train) + len(X_test) == len(X)
assert X_train.index.intersection(X_test.index).empty
assert y_train.mean() > 0
assert y_test.mean() > 0

numerical_preprocessor = Pipeline(
    steps=[
        (
            "median_imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "standard_scaler",
            StandardScaler()
        )
    ]
)

categorical_preprocessor = Pipeline(
    steps=[
        (
            "mode_imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "one_hot_encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            numerical_preprocessor,
            numerical_features
        ),
        (
            "categorical",
            categorical_preprocessor,
            categorical_features
        )
    ],
    remainder="drop"
)

"""# **Logistic Regression**"""

logistic_regression_pipeline = Pipeline(
    steps=[
        (
            "preprocessing",
            preprocessor
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                solver="liblinear",
                random_state=RANDOM_STATE
            )
        )
    ]
)

logistic_regression_pipeline.fit(
    X_train,
    y_train
)

logistic_predictions = (
    logistic_regression_pipeline.predict(X_test)
)

logistic_probabilities = (
    logistic_regression_pipeline.predict_proba(X_test)[:, 1]
)

print("Logistic Regression predictions generated.")
print("Predicted legitimate claims:", (logistic_predictions == 0).sum())
print("Predicted fraudulent claims:", (logistic_predictions == 1).sum())

logistic_accuracy = accuracy_score(
    y_test,
    logistic_predictions
)

print(
    "Logistic Regression accuracy:",
    f"{logistic_accuracy:.4f}"
)

print(
    "Logistic Regression accuracy percentage:",
    f"{logistic_accuracy * 100:.2f}%"
)

print("LOGISTIC REGRESSION CLASSIFICATION REPORT")
print("=" * 50)

logistic_classification_report = classification_report(
    y_test,
    logistic_predictions,
    target_names=[
        "Legitimate",
        "Fraudulent"
    ],
    zero_division=0
)

print(logistic_classification_report)

logistic_report_table = pd.DataFrame(
    classification_report(
        y_test,
        logistic_predictions,
        target_names=[
            "Legitimate",
            "Fraudulent"
        ],
        output_dict=True,
        zero_division=0
    )
).transpose()

display(logistic_report_table.round(4))

logistic_log_loss = log_loss(
    y_test,
    logistic_probabilities
)

print(
    "Logistic Regression log loss:",
    f"{logistic_log_loss:.6f}"
)

logistic_confusion_matrix = confusion_matrix(
    y_test,
    logistic_predictions,
    labels=[0, 1]
)

logistic_tn, logistic_fp, logistic_fn, logistic_tp = (
    logistic_confusion_matrix.ravel()
)

print("Logistic Regression confusion matrix:")
print(logistic_confusion_matrix)

print("\nTrue negatives:", logistic_tn)
print("False positives:", logistic_fp)
print("False negatives:", logistic_fn)
print("True positives:", logistic_tp)

fig, axis = plt.subplots(figsize=(7, 6))

display_matrix = ConfusionMatrixDisplay(
    confusion_matrix=logistic_confusion_matrix,
    display_labels=[
        "Legitimate",
        "Fraudulent"
    ]
)

display_matrix.plot(
    cmap="Blues",
    values_format=",d",
    colorbar=False,
    ax=axis
)

axis.set_title(
    "Logistic Regression confusion matrix",
    fontsize=14,
    fontweight="bold",
    pad=14
)

axis.set_xlabel("Predicted class")
axis.set_ylabel("Actual class")

plt.tight_layout()
plt.show()

logistic_roc_auc = roc_auc_score(
    y_test,
    logistic_probabilities
)

logistic_fpr_curve, logistic_tpr_curve, logistic_thresholds = (
    roc_curve(
        y_test,
        logistic_probabilities
    )
)

print(
    "Logistic Regression ROC-AUC:",
    f"{logistic_roc_auc:.4f}"
)

fig, axis = plt.subplots(figsize=(8, 6))

axis.plot(
    logistic_fpr_curve,
    logistic_tpr_curve,
    color="#0077B6",
    linewidth=3,
    label=(
        "Logistic Regression "
        f"(AUC = {logistic_roc_auc:.3f})"
    )
)

axis.plot(
    [0, 1],
    [0, 1],
    color="#D62828",
    linestyle="--",
    linewidth=2,
    label="Random classifier (AUC = 0.500)"
)

axis.fill_between(
    logistic_fpr_curve,
    logistic_tpr_curve,
    alpha=0.15,
    color="#0077B6"
)

axis.text(
    0.62,
    0.20,
    f"ROC-AUC = {logistic_roc_auc:.3f}",
    fontsize=11,
    bbox={
        "facecolor": "white",
        "edgecolor": "#0077B6",
        "boxstyle": "round,pad=0.4"
    }
)

axis.set_title(
    "Logistic Regression ROC curve",
    fontsize=14,
    fontweight="bold"
)

axis.set_xlabel("False-positive rate")
axis.set_ylabel("True-positive rate")
axis.set_xlim(0, 1)
axis.set_ylim(0, 1.02)
axis.legend(loc="lower right")

plt.tight_layout()
plt.show()

"""## **Logistic Regression false-positive rate**"""

logistic_false_positive_rate = (
    logistic_fp / (logistic_fp + logistic_tn)
    if (logistic_fp + logistic_tn) > 0
    else np.nan
)

print(
    "Logistic Regression false-positive rate:",
    f"{logistic_false_positive_rate:.2%}"
)

"""# **XGBoost Classifier**"""

number_of_legitimate_training_claims = int(
    (y_train == 0).sum()
)

number_of_fraudulent_training_claims = int(
    (y_train == 1).sum()
)

scale_positive_weight = (
    number_of_legitimate_training_claims
    / number_of_fraudulent_training_claims
)

print(
    "Legitimate training claims:",
    number_of_legitimate_training_claims
)

print(
    "Fraudulent training claims:",
    number_of_fraudulent_training_claims
)

print(
    "XGBoost scale_pos_weight:",
    f"{scale_positive_weight:.4f}"
)

xgboost_pipeline = Pipeline(
    steps=[
        (
            "preprocessing",
            preprocessor
        ),
        (
            "classifier",
            XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                n_estimators=300,
                learning_rate=0.05,
                max_depth=4,
                min_child_weight=3,
                subsample=0.80,
                colsample_bytree=0.80,
                reg_alpha=0.10,
                reg_lambda=1.00,
                scale_pos_weight=scale_positive_weight,
                random_state=RANDOM_STATE,
                n_jobs=-1
            )
        )
    ]
)

print("XGBoost pipeline created.")

xgboost_pipeline.fit(
    X_train,
    y_train
)

xgboost_predictions = (
    xgboost_pipeline.predict(X_test)
)

xgboost_probabilities = (
    xgboost_pipeline.predict_proba(X_test)[:, 1]
)

print("XGBoost predictions generated.")
print("Predicted legitimate claims:", (xgboost_predictions == 0).sum())
print("Predicted fraudulent claims:", (xgboost_predictions == 1).sum())

xgboost_accuracy = accuracy_score(
    y_test,
    xgboost_predictions
)

print(
    "XGBoost accuracy:",
    f"{xgboost_accuracy:.4f}"
)

print(
    "XGBoost accuracy percentage:",
    f"{xgboost_accuracy * 100:.2f}%"
)

print("XGBOOST CLASSIFICATION REPORT")
print("=" * 50)

xgboost_classification_report = classification_report(
    y_test,
    xgboost_predictions,
    target_names=[
        "Legitimate",
        "Fraudulent"
    ],
    zero_division=0
)

print(xgboost_classification_report)

xgboost_report_table = pd.DataFrame(
    classification_report(
        y_test,
        xgboost_predictions,
        target_names=[
            "Legitimate",
            "Fraudulent"
        ],
        output_dict=True,
        zero_division=0
    )
).transpose()

display(xgboost_report_table.round(4))

xgboost_log_loss = log_loss(
    y_test,
    xgboost_probabilities
)

print(
    "XGBoost log loss:",
    f"{xgboost_log_loss:.6f}"
)

xgboost_confusion_matrix = confusion_matrix(
    y_test,
    xgboost_predictions,
    labels=[0, 1]
)

xgboost_tn, xgboost_fp, xgboost_fn, xgboost_tp = (
    xgboost_confusion_matrix.ravel()
)

print("XGBoost confusion matrix:")
print(xgboost_confusion_matrix)

print("\nTrue negatives:", xgboost_tn)
print("False positives:", xgboost_fp)
print("False negatives:", xgboost_fn)
print("True positives:", xgboost_tp)

fig, axis = plt.subplots(figsize=(7, 6))

display_matrix = ConfusionMatrixDisplay(
    confusion_matrix=xgboost_confusion_matrix,
    display_labels=[
        "Legitimate",
        "Fraudulent"
    ]
)

display_matrix.plot(
    cmap="Oranges",
    values_format=",d",
    colorbar=False,
    ax=axis
)

axis.set_title(
    "XGBoost confusion matrix",
    fontsize=14,
    fontweight="bold",
    pad=14
)

axis.set_xlabel("Predicted class")
axis.set_ylabel("Actual class")

plt.tight_layout()
plt.show()

xgboost_roc_auc = roc_auc_score(
    y_test,
    xgboost_probabilities
)

xgboost_fpr_curve, xgboost_tpr_curve, xgboost_thresholds = (
    roc_curve(
        y_test,
        xgboost_probabilities
    )
)

print(
    "XGBoost ROC-AUC:",
    f"{xgboost_roc_auc:.4f}"
)

fig, axis = plt.subplots(figsize=(8, 6))

axis.plot(
    xgboost_fpr_curve,
    xgboost_tpr_curve,
    color="#9B2226",
    linewidth=3,
    label=(
        "XGBoost "
        f"(AUC = {xgboost_roc_auc:.3f})"
    )
)

axis.plot(
    [0, 1],
    [0, 1],
    color="#2A9D8F",
    linestyle="--",
    linewidth=2,
    label="Random classifier (AUC = 0.500)"
)

axis.fill_between(
    xgboost_fpr_curve,
    xgboost_tpr_curve,
    alpha=0.15,
    color="#9B2226"
)

axis.text(
    0.62,
    0.20,
    f"ROC-AUC = {xgboost_roc_auc:.3f}",
    fontsize=11,
    bbox={
        "facecolor": "white",
        "edgecolor": "#9B2226",
        "boxstyle": "round,pad=0.4"
    }
)

axis.set_title(
    "XGBoost ROC curve",
    fontsize=14,
    fontweight="bold"
)

axis.set_xlabel("False-positive rate")
axis.set_ylabel("True-positive rate")
axis.set_xlim(0, 1)
axis.set_ylim(0, 1.02)
axis.legend(loc="lower right")

plt.tight_layout()
plt.show()

xgboost_false_positive_rate = (
    xgboost_fp / (xgboost_fp + xgboost_tn)
    if (xgboost_fp + xgboost_tn) > 0
    else np.nan
)

print(
    "XGBoost false-positive rate:",
    f"{xgboost_false_positive_rate:.2%}"
)